//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infaestructura.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleVenta
    {
        public int id { get; set; }
        public int idProducto { get; set; }
        public int cantidad { get; set; }
        public double subtotal { get; set; }
    
        public virtual Productos Productos { get; set; }
    }
}
